// clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livro.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})


export class LivroListaComponent implements OnInit {
  public editoras: Array<Editora> = [];
  public livros: Array<Livro> = [];

  constructor(private servEditora: ControleEditoraService, private servLivros: ControleLivrosService) { }

  ngOnInit(): void {
    this.controleLivros.obterTodos()
      .then(livros => this.livros = livros);
  }  

  excluir(codigo: string): void {
    this.controleLivros.excluir(codigo)
      .then(() => this.controleLivros.obterTodos())
      .then(livros => this.livros = livros);
  }  

  incluir(): void {
    this.controleLivros.incluir(this.livro)
      .then(() => this.router.navigateByUrl('/lista'));
  }
}  
<main class="container">
    <h1 class="my-4">Lista de Livros</h1>
    <table class="table">
    <thead>
        <tr>
        <th>Código</th>
        <th>Título</th>
        <th>Editora</th>
        <th>Autores</th>
        <th>Resumo</th>
        <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        <tr *ngFor="let livro of livros">
        <td>{{ livro.codigo }}</td>
        <td>
            {{ livro.titulo }}
        </td>
        <td>{{ obterNome(livro.codEditora) }}</td>
        <td>
            <ul>
              <li *ngFor="let autor of livro.autores">{{ autor }}</li>
            </ul>
        </td>
        <td>{{ livro.resumo }}</td>
        <td>
            <button class="btn btn-danger" (click)="excluir(livro.codigo)">Excluir</button>
        </td>
        </tr>
    </tbody>
    </table>
</main>

// clientes/livros-react/src/LivroLista.js
import { useState, useEffect } from 'react';
import ControleLivros from './controle/ControleLivros';
import ControleEditora from './controle/ControleEditora';

function LinhaLivro(props) {
  const controleEditora = new ControleEditora();
  const nomeEditora = controleEditora.getNomeEditora(props.livro.codEditora);
  return (
    <tr>
      <td>{props.livro.titulo}</td>
      <td>{props.livro.resumo}</td>
      <td>{nomeEditora}</td>
      <td>
        <ul>
          {props.livro.autores.map((autor, index) => (
            <li key={index}>{autor}</li>
          ))}
        </ul>
      </td>
      <td>
        <button className="btn btn-danger" onClick={() => props.excluir(props.livro.codigo)}>Excluir</button>
      </td>
    </tr>
  );
}

export default function LivroLista() {
  const [livros, setLivros] = useState([]);
  const [carregado, setCarregado] = useState(false);

  useEffect(() => {
    controle.obterTodos().then((resultado) => setLivros(resultado));
    async function carregarLivros() {
      const controleLivros = new ControleLivros();
      const livros = await controleLivros.obterLivros();
      setLivros(livros);
      setCarregado(true);
    }
    if (!carregado) {
      carregarLivros();
    }
  }, [carregado]);

  const excluir = async (codigo) => {
    const controleLivros = new ControleLivros();
    await controleLivros.excluir(codigo).then(() => setCarregado(false));
  };

  return (
    <main className=''>
      <h1>Catálogo de Livros</h1>
      <table className='table w-100 mx-auto'>
        <thead>
          <tr className='text-light bg-dark'>
            <th>Título</th>
            <th>Resumo</th>
            <th>Editora</th>
            <th>Autores</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {livros.map((livro) => (
            <LinhaLivro key={index} livro={livro} excluir={excluir} />
          ))}
        </tbody>
      </table>
    </main>
  );
}
