// clientes/livros-react/src/LivroDados.js
  import React, { useState } from 'react';
  import { useNavigate } from 'react-router-dom';
  import ControleLivros from './controle/ControleLivros';
  import ControleEditora from './controle/ControleEditora';

  function LivroDados() {
    const controleLivro = new ControleLivros();
    const controleEditora = new ControleEditora();
    const opcoes = controleEditora.getEditoras().map((editora) => {
      return { value: editora.codEditora, text: editora.nome };
    });

    const [titulo, setTitulo] = useState('');
    const [resumo, setResumo] = useState('');
    const [autores, setAutores] = useState('');
    const [codEditora, setCodEditora] = useState(opcoes[0].value);

    const navigate = useNavigate();

    function tratarCombo(event) {
      setCodEditora(Number(event.target.value));
    }

    function incluir(event) {
      event.preventDefault();
      const livro = {
        codigo: 0,
        titulo: titulo,
        resumo: resumo,
        autores: autores.split('\n'),
        codEditora: codEditora
      };
      async function incluir(livro) {
        livro.codigo = ''; // Utilizando um texto vazio para o código
        await controle.incluir(livro).then(() => navigate('/'));
      }
      

    return (
      <main>
      <h2 className="my-4 text-center">Novo Livro</h2>
      <form onSubmit={incluir} className="row col-6 mx-auto">
        <div className="form-group">
          <label htmlFor="titulo">Título:</label>
          <input type="text" id="titulo" className="form-control" value={titulo} onChange={(event) => setTitulo(event.target.value)} />
        </div>
        <div className="form-group">
          <label htmlFor="resumo">Resumo:</label>
          <textarea id="resumo" className="form-control" value={resumo} onChange={(event) => setResumo(event.target.value)} />
        </div>
        <div className="form-group">
          <label htmlFor="autores">Autores:</label>
          <textarea id="autores" className="form-control" value={autores} onChange={(event) => setAutores(event.target.value)} />
        </div>
        <div className="form-group">
          <label htmlFor="codEditora">Editora:</label>
          <select id="codEditora" className="form-control" value={codEditora} onChange={tratarCombo}>
            {opcoes.map((opcao) => (
              <option key={opcao.value} value={opcao.value}>
                {opcao.text}
              </option>
            ))}
          </select>
        </div>
        <button type="submit" className="btn btn-primary mt-4">Incluir</button>
      </form>
    </main>
  );
  }
  }
  export default LivroDados;

// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livro.service';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {
  livro: Livro = new Livro(0, 0, '', '', []);
  autoresForm: string = '';
  editoras: Array<Editora> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = () => {
    this.livro.autores = this.autoresForm.split('\n');
    this.servLivros.incluir(this.livro);
    this.router.navigateByUrl('/lista');
  }
}

<main class="container">
    <h2>Cadastro de Livro</h2>
    <form (submit)="incluir()" ngNativeValidate>
        <div class="form-group">
            <label for="titulo">Título:</label>
            <input type="text" id="titulo" class="form-control" [(ngModel)]="livro.titulo" name="titulo" required>
        </div>
        <div class="form-group">
            <label for="resumo">Resumo:</label>
            <textarea id="resumo" class="form-control" [(ngModel)]="livro.resumo" name="resumo" required></textarea>
        </div>
        <div class="form-group">
            <label for="editora">Editora:</label>
            <select id="editora" class="form-control" [(ngModel)]="livro.codEditora" name="editora" required>
                <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{ editora.nome }}</option>
            </select>
        </div>
        <div class="form-group">
            <label for="autores">Autores:</label>
            <textarea id="autores" class="form-control" [(ngModel)]="autoresForm" name="autores"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Salvar</button>
    </form>
</main>
